'use strict';
/**
 * 
 */
angular.module('sbAdminApp').controller('jsonEditorCtrl', function($scope, $http, api, $sce, $window, $cookieStore) {
	$scope.alert = "  Loading Data will take some time.....";

	$scope.closeAlert = function(argument) {
		$scope.alert = false;
	};


	// var travel = {};
	$scope.purchase = {
		address: "AMAZON",
		msgType: "purchase",
		msgSubType: "order-delivered",
		merchantName: "Amazon",
		pattern: "",
		orderStatus: "Order Delivered",
		orderDate: "",
		dateFormat: "",
		posProductName: 1,
		posQuantity: -1,
		posDeliveryDetails: -1,
		posAmount: -1,
		posManageLink: -1,
		posExpectedDate: -1,
		posAwbNumber: -1,
		posDeliveryDate: -1,
		posDeliveryTime: -1,
		posShipmentId: -1,
		posOrderId: -1,
		posCourierName: -1,
		posSellerName: -1,
		posShipmentDate: -1,
		posReferenceNumber: -1,
		posPickupDate: -1,
		posProcessingDays: -1,
		posInitiationDate: -1,
		posMerchantName: -1,
		posProductDetails: -1,
		posAltExpectedDate: -1,
		Count: 0,
		dateModified: new Date(),
		dateCreated: new Date(),
		dateLastReprocessed: new Date(),
		dateReprocessSet: new Date(),
		regexDate: "",
		id: "",
		posReverseOrderPickupTime: -1,
		posOrderReturnReceiveDate: -1,
		posDeliveryFailReason: -1,
	};


	$scope.travel = {

		posBookingId: -1,
		posCouponValue: -1,
		posSellerName: -1,
		posDeliveryDate: -1,
		posLink: -1,
		posProductName: -1,
		posDestination: -1,
		posDeliveryTime: -1,
		dateModified: new Date(),
		bookingType: "",
		posQuantity: -1,
		posDeliveryFailReason: -1,
		posAwbNumber: -1,
		merchantName: "IRCTC",
		merchantCode: "IR",
		posClass: -1,
		dateFormat: "dd-MM-yy",
		posFlightId: -1,
		posReverseOrderPickupTime: -1,
		posAmount: -1,
		posDeliveryDetails: -1,
		posEmailID: -1,
		msgType: "travel",
		posSeatNo: -1,
		posTotalBalance: -1,
		posReferenceNumber: -1,
		posPNR: -1,
		posDate: -1,
		posShipmentId: -1,
		posShipmentDate: -1,
		posSurcharge: -1,
		posOrderId: -1,
		posDuration: -1,
		posCarNumber: -1,
		dateCreated: "2016-05-12T17:09:30.183000",
		posCourierName: -1,
		posExpectedDate: -1,
		posPickupDate: -1,
		posSource: -1,
		accountType: "",
		address: "IRCTCI",
		timeFormat: "HH:mm",
		msgSubType: "travel",
		posProductDescription: -1,
		posProcessingDays: -1,
		posArrivalTime: -1,
		posTime: -1,
		posStatus: -1,
		posSRN: -1,
		paymentType: "",
		posSenderName: -1,
		posCode: 1,
		posEndDate: -1,
		posInitiationDate: -1,
		posHelpline: -1,
		posTrainId: -1,
		posCarrieName: -1,
		posManageLink: -1,
		posCRN: -1,
		txnType: "",
		posReturnOrderReceiveDate: -1,
		posLandMark: -1,
		pattern: "",
		ignoreMsg: false,
		posAccountId: -1,
		posOrderDate: -1,
		dateLastReprocessed: "",
		dateReprocessSet: "",
		Count: 3,
		regexDate: new Date(),
		posGateNo: -1,
		posReturnFlightId: -1,
		posReturnPNR: -1,
		posReturnDate: -1,
		posReturnEndDate: -1,
		posReturnSource: -1,
		posReturnDestination: -1,
		posReturnTime: -1,
		posReturnArrivalTime: -1,
		isReturn: false,
		posSourceTerminal: -1,
		posDestinationTerminal: -1
	};



});